library(lubridate)
my_date <- ymd("1989-05-17")
hms("03:22:14" )
ymd(dt2)
update(this_moment, hours = 8, minutes = 34, seconds = 55)
nyc <- now(tzone = "America/New_York")
depart <- nyc + days(2)
depart <- update(depart, hours = 17, minutes = 34)
arrive <- depart + hours(15) + minutes(50)
arrive <- with_tz(arrive, tzone = "Asia/Hong_Kong")
last_time <- mdy("June 17, 2008", tz = "Singapore")
how_long <- new_interval(last_time,arrive)
