library(data.table)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv", destfile = "data.csv")
data <- read.csv("data.csv", header = T)
name = names(data)
split = strsplit(name, "wgtp")
split[123]
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", destfile = "GDP.csv")
gdp <- read.csv("GDP.csv", skip = 5, header = F)
str(gdp)
gdp <- gdp[c(1:190), ]
gdp$V5 <- as.numeric(gsub(",", "", gdp$V5))
grep("^United", gdp$V4)
table(grepl("^United", gdp$V4))
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv", destfile = "edu.csv")
edu <-read.csv("edu.csv", header = T)
merged <- merge(gdp, edu, by.x = "V1", by.y = "CountryCode")
table(grepl("Fiscal year end: June",merged$Special.Notes))
library(quantmod)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn)
sampleTimes <- as.Date(sampleTimes)
year <- year(sampleTimes)
weekofday <- wday(sampleTimes)
table(year, weekofday)
